-- MySQL Script generated by MySQL Workbench
-- Sun Oct  3 16:32:39 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema tcc
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema tcc
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `tcc` DEFAULT CHARACTER SET utf8 ;
USE `tcc` ;

-- -----------------------------------------------------
-- Table `tcc`.`evento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tcc`.`evento` (
  `id_evento` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `descricao` VARCHAR(250) NULL,
  `imagem` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_evento`))
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `tcc`.`adocao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tcc`.`adocao` (
  `id_adocao` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `contato` VARCHAR(45) NOT NULL,
  `cpf` VARCHAR(45) NOT NULL,
  `rg` VARCHAR(45) NOT NULL,
  `cidade` VARCHAR(45) NOT NULL,
  `bairro` VARCHAR(45) NOT NULL,
  `rua` VARCHAR(45) NOT NULL,
  `numero` INT NOT NULL,
  `complemento` VARCHAR(45) NULL,
  `nome_animal` VARCHAR(45) NOT NULL,
  `data_adocao` DATE NOT NULL,
  PRIMARY KEY (`id_adocao`))
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `tcc`.`animal`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tcc`.`animal` (
  `id_animal` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `descricao` VARCHAR(45) NULL,
  `imagem` VARCHAR(45) NOT NULL,
  `status` TINYINT NOT NULL,
  `especie` VARCHAR(45) NOT NULL,
  `sexo` VARCHAR(45) NOT NULL,
  `raca` VARCHAR(45) NOT NULL,
  `porte` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_animal`))
ENGINE = InnoDB;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
